<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityRegionsProxy extends \MyApp\GlobalBundle\Entity\Regions implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getFullPicturePath()
    {
        $this->__load();
        return parent::getFullPicturePath();
    }

    public function getFullPicturePath2()
    {
        $this->__load();
        return parent::getFullPicturePath2();
    }

    public function uploadPicture()
    {
        $this->__load();
        return parent::uploadPicture();
    }

    public function uploadPicture2()
    {
        $this->__load();
        return parent::uploadPicture2();
    }

    public function movePicture()
    {
        $this->__load();
        return parent::movePicture();
    }

    public function removePicture()
    {
        $this->__load();
        return parent::removePicture();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNomFr($nomFr)
    {
        $this->__load();
        return parent::setNomFr($nomFr);
    }

    public function getNomFr()
    {
        $this->__load();
        return parent::getNomFr();
    }

    public function setNomEn($nomEn)
    {
        $this->__load();
        return parent::setNomEn($nomEn);
    }

    public function getNomEn()
    {
        $this->__load();
        return parent::getNomEn();
    }

    public function setUrlFr($urlFr)
    {
        $this->__load();
        return parent::setUrlFr($urlFr);
    }

    public function getUrlFr()
    {
        $this->__load();
        return parent::getUrlFr();
    }

    public function setUrlEn($urlEn)
    {
        $this->__load();
        return parent::setUrlEn($urlEn);
    }

    public function getUrlEn()
    {
        $this->__load();
        return parent::getUrlEn();
    }

    public function setTitreFr($titreFr)
    {
        $this->__load();
        return parent::setTitreFr($titreFr);
    }

    public function getTitreFr()
    {
        $this->__load();
        return parent::getTitreFr();
    }

    public function setTitreEn($titreEn)
    {
        $this->__load();
        return parent::setTitreEn($titreEn);
    }

    public function getTitreEn()
    {
        $this->__load();
        return parent::getTitreEn();
    }

    public function setTexteFr($texteFr)
    {
        $this->__load();
        return parent::setTexteFr($texteFr);
    }

    public function getTexteFr()
    {
        $this->__load();
        return parent::getTexteFr();
    }

    public function setTexteEn($texteEn)
    {
        $this->__load();
        return parent::setTexteEn($texteEn);
    }

    public function getTexteEn()
    {
        $this->__load();
        return parent::getTexteEn();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setImageHautFr($imageHautFr)
    {
        $this->__load();
        return parent::setImageHautFr($imageHautFr);
    }

    public function getImageHautFr()
    {
        $this->__load();
        return parent::getImageHautFr();
    }

    public function setImageHautEn($imageHautEn)
    {
        $this->__load();
        return parent::setImageHautEn($imageHautEn);
    }

    public function getImageHautEn()
    {
        $this->__load();
        return parent::getImageHautEn();
    }

    public function setImageGauche($imageGauche)
    {
        $this->__load();
        return parent::setImageGauche($imageGauche);
    }

    public function getImageGauche()
    {
        $this->__load();
        return parent::getImageGauche();
    }

    public function setImageCentre($imageCentre)
    {
        $this->__load();
        return parent::setImageCentre($imageCentre);
    }

    public function getImageCentre()
    {
        $this->__load();
        return parent::getImageCentre();
    }

    public function setTexteFrBasPage($texteFrBasPage)
    {
        $this->__load();
        return parent::setTexteFrBasPage($texteFrBasPage);
    }

    public function getTexteFrBasPage()
    {
        $this->__load();
        return parent::getTexteFrBasPage();
    }

    public function setTexteEnBasPage($texteEnBasPage)
    {
        $this->__load();
        return parent::setTexteEnBasPage($texteEnBasPage);
    }

    public function getTexteEnBasPage()
    {
        $this->__load();
        return parent::getTexteEnBasPage();
    }

    public function setImageTravel($imageTravel)
    {
        $this->__load();
        return parent::setImageTravel($imageTravel);
    }

    public function getImageTravel()
    {
        $this->__load();
        return parent::getImageTravel();
    }

    public function setImageTravelDoctrine($imageTravelDoctrine)
    {
        $this->__load();
        return parent::setImageTravelDoctrine($imageTravelDoctrine);
    }

    public function getImageTravelDoctrine()
    {
        $this->__load();
        return parent::getImageTravelDoctrine();
    }

    public function setResumeFrTravel($resumeFrTravel)
    {
        $this->__load();
        return parent::setResumeFrTravel($resumeFrTravel);
    }

    public function getResumeFrTravel()
    {
        $this->__load();
        return parent::getResumeFrTravel();
    }

    public function setResumeEnTravel($resumeEnTravel)
    {
        $this->__load();
        return parent::setResumeEnTravel($resumeEnTravel);
    }

    public function getResumeEnTravel()
    {
        $this->__load();
        return parent::getResumeEnTravel();
    }

    public function setPageMetakeywordFr($pageMetakeywordFr)
    {
        $this->__load();
        return parent::setPageMetakeywordFr($pageMetakeywordFr);
    }

    public function getPageMetakeywordFr()
    {
        $this->__load();
        return parent::getPageMetakeywordFr();
    }

    public function setPageMetakeywordEn($pageMetakeywordEn)
    {
        $this->__load();
        return parent::setPageMetakeywordEn($pageMetakeywordEn);
    }

    public function getPageMetakeywordEn()
    {
        $this->__load();
        return parent::getPageMetakeywordEn();
    }

    public function setPageMetadescriptionFr($pageMetadescriptionFr)
    {
        $this->__load();
        return parent::setPageMetadescriptionFr($pageMetadescriptionFr);
    }

    public function getPageMetadescriptionFr()
    {
        $this->__load();
        return parent::getPageMetadescriptionFr();
    }

    public function setPageMetadescriptionEn($pageMetadescriptionEn)
    {
        $this->__load();
        return parent::setPageMetadescriptionEn($pageMetadescriptionEn);
    }

    public function getPageMetadescriptionEn()
    {
        $this->__load();
        return parent::getPageMetadescriptionEn();
    }

    public function setTexteAccueilFr($texteAccueilFr)
    {
        $this->__load();
        return parent::setTexteAccueilFr($texteAccueilFr);
    }

    public function getTexteAccueilFr()
    {
        $this->__load();
        return parent::getTexteAccueilFr();
    }

    public function setTexteAccueilEn($texteAccueilEn)
    {
        $this->__load();
        return parent::setTexteAccueilEn($texteAccueilEn);
    }

    public function getTexteAccueilEn()
    {
        $this->__load();
        return parent::getTexteAccueilEn();
    }

    public function setImageSuggestion($imageSuggestion)
    {
        $this->__load();
        return parent::setImageSuggestion($imageSuggestion);
    }

    public function getImageSuggestion()
    {
        $this->__load();
        return parent::getImageSuggestion();
    }

    public function setImageDoctrine($imageDoctrine)
    {
        $this->__load();
        return parent::setImageDoctrine($imageDoctrine);
    }

    public function getImageDoctrine()
    {
        $this->__load();
        return parent::getImageDoctrine();
    }

    public function setReservitId($reservitId)
    {
        $this->__load();
        return parent::setReservitId($reservitId);
    }

    public function getReservitId()
    {
        $this->__load();
        return parent::getReservitId();
    }

    public function setAffiche($affiche)
    {
        $this->__load();
        return parent::setAffiche($affiche);
    }

    public function getAffiche()
    {
        $this->__load();
        return parent::getAffiche();
    }

    public function setProvinceEtatId(\MyApp\GlobalBundle\Entity\Provinces_etats $provinceEtatId)
    {
        $this->__load();
        return parent::setProvinceEtatId($provinceEtatId);
    }

    public function getProvinceEtatId()
    {
        $this->__load();
        return parent::getProvinceEtatId();
    }

    public function addQcs_saisons(\MyApp\GlobalBundle\Entity\Qcs_saisons $qcsSaisonId)
    {
        $this->__load();
        return parent::addQcs_saisons($qcsSaisonId);
    }

    public function getQcsSaisonId()
    {
        $this->__load();
        return parent::getQcsSaisonId();
    }

    public function addAppel_Offre(\MyApp\GlobalBundle\Entity\Appel_Offre $regionAppelOffre)
    {
        $this->__load();
        return parent::addAppel_Offre($regionAppelOffre);
    }

    public function getRegionAppelOffre()
    {
        $this->__load();
        return parent::getRegionAppelOffre();
    }

    public function addTexte_region_categorie(\MyApp\GlobalBundle\Entity\Texte_region_categorie $texteRegionCategorie)
    {
        $this->__load();
        return parent::addTexte_region_categorie($texteRegionCategorie);
    }

    public function getTexteRegionCategorie()
    {
        $this->__load();
        return parent::getTexteRegionCategorie();
    }

    public function addTexte_region_attrait(\MyApp\GlobalBundle\Entity\Texte_region_attrait $texteRegionAttrait)
    {
        $this->__load();
        return parent::addTexte_region_attrait($texteRegionAttrait);
    }

    public function getTexteRegionAttrait()
    {
        $this->__load();
        return parent::getTexteRegionAttrait();
    }

    public function addTexte_region_sante(\MyApp\GlobalBundle\Entity\Texte_region_sante $texteRegionSante)
    {
        $this->__load();
        return parent::addTexte_region_sante($texteRegionSante);
    }

    public function getTexteRegionSante()
    {
        $this->__load();
        return parent::getTexteRegionSante();
    }

    public function addTexte_region_restaurant(\MyApp\GlobalBundle\Entity\Texte_region_restaurant $texteRegionRestaurant)
    {
        $this->__load();
        return parent::addTexte_region_restaurant($texteRegionRestaurant);
    }

    public function getTexteRegionRestaurant()
    {
        $this->__load();
        return parent::getTexteRegionRestaurant();
    }

    public function addZones(\MyApp\GlobalBundle\Entity\Zones $zoneId)
    {
        $this->__load();
        return parent::addZones($zoneId);
    }

    public function getZoneId()
    {
        $this->__load();
        return parent::getZoneId();
    }

    public function addTexte_region_forfait(\MyApp\GlobalBundle\Entity\Texte_region_forfait $texteRegionForfait)
    {
        $this->__load();
        return parent::addTexte_region_forfait($texteRegionForfait);
    }

    public function getTexteRegionForfait()
    {
        $this->__load();
        return parent::getTexteRegionForfait();
    }

    public function addQcs_regions_vedettes(\MyApp\GlobalBundle\Entity\Qcs_regions_vedettes $qcsRegionVedetteId)
    {
        $this->__load();
        return parent::addQcs_regions_vedettes($qcsRegionVedetteId);
    }

    public function getQcsRegionVedetteId()
    {
        $this->__load();
        return parent::getQcsRegionVedetteId();
    }

    public function addHebergements(\MyApp\GlobalBundle\Entity\Hebergements $hebergementId)
    {
        $this->__load();
        return parent::addHebergements($hebergementId);
    }

    public function getHebergementId()
    {
        $this->__load();
        return parent::getHebergementId();
    }

    public function addAttraits(\MyApp\GlobalBundle\Entity\Attraits $attraitId)
    {
        $this->__load();
        return parent::addAttraits($attraitId);
    }

    public function getAttraitId()
    {
        $this->__load();
        return parent::getAttraitId();
    }

    public function addVilles(\MyApp\GlobalBundle\Entity\Villes $villeId)
    {
        $this->__load();
        return parent::addVilles($villeId);
    }

    public function getVilleId()
    {
        $this->__load();
        return parent::getVilleId();
    }

    public function setRepertoireFr($repertoireFr)
    {
        $this->__load();
        return parent::setRepertoireFr($repertoireFr);
    }

    public function getRepertoireFr()
    {
        $this->__load();
        return parent::getRepertoireFr();
    }

    public function setRepertoireEn($repertoireEn)
    {
        $this->__load();
        return parent::setRepertoireEn($repertoireEn);
    }

    public function getRepertoireEn()
    {
        $this->__load();
        return parent::getRepertoireEn();
    }

    public function setNomReservit($nomReservit)
    {
        $this->__load();
        return parent::setNomReservit($nomReservit);
    }

    public function getNomReservit()
    {
        $this->__load();
        return parent::getNomReservit();
    }

    public function addTexte_region_corporatif(\MyApp\GlobalBundle\Entity\Texte_region_corporatif $texteRegionCorporatif)
    {
        $this->__load();
        return parent::addTexte_region_corporatif($texteRegionCorporatif);
    }

    public function getTexteRegionCorporatif()
    {
        $this->__load();
        return parent::getTexteRegionCorporatif();
    }

    public function addTexte_region_appel_offre(\MyApp\GlobalBundle\Entity\Texte_region_appel_offre $texteRegionAppelOffre)
    {
        $this->__load();
        return parent::addTexte_region_appel_offre($texteRegionAppelOffre);
    }

    public function getTexteRegionAppelOffre()
    {
        $this->__load();
        return parent::getTexteRegionAppelOffre();
    }

    public function addTexte_region_chambre_affaire(\MyApp\GlobalBundle\Entity\Texte_region_chambre_affaire $texteRegionChambreAffaire)
    {
        $this->__load();
        return parent::addTexte_region_chambre_affaire($texteRegionChambreAffaire);
    }

    public function getTexteRegionChambreAffaire()
    {
        $this->__load();
        return parent::getTexteRegionChambreAffaire();
    }

    public function addTexte_region_forfait_affaire(\MyApp\GlobalBundle\Entity\Texte_region_forfait_affaire $texteRegionForfaitAffaire)
    {
        $this->__load();
        return parent::addTexte_region_forfait_affaire($texteRegionForfaitAffaire);
    }

    public function getTexteRegionForfaitAffaire()
    {
        $this->__load();
        return parent::getTexteRegionForfaitAffaire();
    }

    public function addTexte_region_location_salle(\MyApp\GlobalBundle\Entity\Texte_region_location_salle $texteRegionLocationSalle)
    {
        $this->__load();
        return parent::addTexte_region_location_salle($texteRegionLocationSalle);
    }

    public function getTexteRegionLocationSalle()
    {
        $this->__load();
        return parent::getTexteRegionLocationSalle();
    }

    public function addTexte_region_activite_corporative(\MyApp\GlobalBundle\Entity\Texte_region_activite_corporative $texteRegionActiviteCorporative)
    {
        $this->__load();
        return parent::addTexte_region_activite_corporative($texteRegionActiviteCorporative);
    }

    public function getTexteRegionActiviteCorporative()
    {
        $this->__load();
        return parent::getTexteRegionActiviteCorporative();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'province_etat_id', 'qcs_saison_id', 'region_appel_offre', 'texte_region_categorie', 'texte_region_corporatif', 'texte_region_appel_offre', 'texte_region_chambre_affaire', 'texte_region_forfait_affaire', 'texte_region_location_salle', 'texte_region_activite_corporative', 'texte_region_attrait', 'texte_region_sante', 'texte_region_restaurant', 'nom_reservit', 'nom_fr', 'nom_en', 'url_fr', 'url_en', 'titre_fr', 'titre_en', 'repertoire_fr', 'repertoire_en', 'texte_fr', 'texte_en', 'latitude', 'longitude', 'image_haut_fr', 'image_haut_en', 'image_gauche', 'image_centre', 'texte_fr_bas_page', 'texte_en_bas_page', 'image_travel', 'image_travel_doctrine', 'resume_fr_travel', 'resume_en_travel', 'page_metakeyword_fr', 'page_metakeyword_en', 'page_metadescription_fr', 'page_metadescription_en', 'texte_accueil_fr', 'texte_accueil_en', 'image_suggestion', 'image_doctrine', 'reservit_id', 'affiche', 'zone_id', 'texte_region_forfait', 'qcs_region_vedette_id', 'hebergement_id', 'attrait_id', 'ville_id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}