<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityForfaitsProxy extends \MyApp\GlobalBundle\Entity\Forfaits implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getFullPicturePath()
    {
        $this->__load();
        return parent::getFullPicturePath();
    }

    public function uploadPicture()
    {
        $this->__load();
        return parent::uploadPicture();
    }

    public function movePicture()
    {
        $this->__load();
        return parent::movePicture();
    }

    public function removePicture()
    {
        $this->__load();
        return parent::removePicture();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNomFr($nomFr)
    {
        $this->__load();
        return parent::setNomFr($nomFr);
    }

    public function getNomFr()
    {
        $this->__load();
        return parent::getNomFr();
    }

    public function setNomEn($nomEn)
    {
        $this->__load();
        return parent::setNomEn($nomEn);
    }

    public function getNomEn()
    {
        $this->__load();
        return parent::getNomEn();
    }

    public function setPageFr($pageFr)
    {
        $this->__load();
        return parent::setPageFr($pageFr);
    }

    public function getPageFr()
    {
        $this->__load();
        return parent::getPageFr();
    }

    public function setPageEn($pageEn)
    {
        $this->__load();
        return parent::setPageEn($pageEn);
    }

    public function getPageEn()
    {
        $this->__load();
        return parent::getPageEn();
    }

    public function setPageTitreFr($pageTitreFr)
    {
        $this->__load();
        return parent::setPageTitreFr($pageTitreFr);
    }

    public function getPageTitreFr()
    {
        $this->__load();
        return parent::getPageTitreFr();
    }

    public function setPageTitreEn($pageTitreEn)
    {
        $this->__load();
        return parent::setPageTitreEn($pageTitreEn);
    }

    public function getPageTitreEn()
    {
        $this->__load();
        return parent::getPageTitreEn();
    }

    public function setPageMetakeywordFr($pageMetakeywordFr)
    {
        $this->__load();
        return parent::setPageMetakeywordFr($pageMetakeywordFr);
    }

    public function getPageMetakeywordFr()
    {
        $this->__load();
        return parent::getPageMetakeywordFr();
    }

    public function setPageMetakeywordEn($pageMetakeywordEn)
    {
        $this->__load();
        return parent::setPageMetakeywordEn($pageMetakeywordEn);
    }

    public function getPageMetakeywordEn()
    {
        $this->__load();
        return parent::getPageMetakeywordEn();
    }

    public function setPageMetadescriptionFr($pageMetadescriptionFr)
    {
        $this->__load();
        return parent::setPageMetadescriptionFr($pageMetadescriptionFr);
    }

    public function getPageMetadescriptionFr()
    {
        $this->__load();
        return parent::getPageMetadescriptionFr();
    }

    public function setPageMetadescriptionEn($pageMetadescriptionEn)
    {
        $this->__load();
        return parent::setPageMetadescriptionEn($pageMetadescriptionEn);
    }

    public function getPageMetadescriptionEn()
    {
        $this->__load();
        return parent::getPageMetadescriptionEn();
    }

    public function setTexteFr($texteFr)
    {
        $this->__load();
        return parent::setTexteFr($texteFr);
    }

    public function getTexteFr()
    {
        $this->__load();
        return parent::getTexteFr();
    }

    public function setTexteEn($texteEn)
    {
        $this->__load();
        return parent::setTexteEn($texteEn);
    }

    public function getTexteEn()
    {
        $this->__load();
        return parent::getTexteEn();
    }

    public function setDefaultForfait($defaultForfait)
    {
        $this->__load();
        return parent::setDefaultForfait($defaultForfait);
    }

    public function getDefaultForfait()
    {
        $this->__load();
        return parent::getDefaultForfait();
    }

    public function setImage($image)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function addQcs_forfaits(\MyApp\GlobalBundle\Entity\Qcs_forfaits $qcsForfaitsId)
    {
        $this->__load();
        return parent::addQcs_forfaits($qcsForfaitsId);
    }

    public function getQcsForfaitsId()
    {
        $this->__load();
        return parent::getQcsForfaitsId();
    }

    public function setQcsSaisonId(\MyApp\GlobalBundle\Entity\Qcs_saisons $qcsSaisonId)
    {
        $this->__load();
        return parent::setQcsSaisonId($qcsSaisonId);
    }

    public function getQcsSaisonId()
    {
        $this->__load();
        return parent::getQcsSaisonId();
    }

    public function addAttraits(\MyApp\GlobalBundle\Entity\Attraits $attraitId)
    {
        $this->__load();
        return parent::addAttraits($attraitId);
    }

    public function getAttraitId()
    {
        $this->__load();
        return parent::getAttraitId();
    }

    public function setImageDoctrine($imageDoctrine)
    {
        $this->__load();
        return parent::setImageDoctrine($imageDoctrine);
    }

    public function getImageDoctrine()
    {
        $this->__load();
        return parent::getImageDoctrine();
    }

    public function addHebergements(\MyApp\GlobalBundle\Entity\Hebergements $hebergementForfait)
    {
        $this->__load();
        return parent::addHebergements($hebergementForfait);
    }

    public function getHebergementForfait()
    {
        $this->__load();
        return parent::getHebergementForfait();
    }

    public function addForfaits_clients(\MyApp\GlobalBundle\Entity\Forfaits_clients $forfaitId)
    {
        $this->__load();
        return parent::addForfaits_clients($forfaitId);
    }

    public function getForfaitId()
    {
        $this->__load();
        return parent::getForfaitId();
    }

    public function setMetaTitreFr($metaTitreFr)
    {
        $this->__load();
        return parent::setMetaTitreFr($metaTitreFr);
    }

    public function getMetaTitreFr()
    {
        $this->__load();
        return parent::getMetaTitreFr();
    }

    public function setMetaTitreEn($metaTitreEn)
    {
        $this->__load();
        return parent::setMetaTitreEn($metaTitreEn);
    }

    public function getMetaTitreEn()
    {
        $this->__load();
        return parent::getMetaTitreEn();
    }

    public function addTexte_region_forfait(\MyApp\GlobalBundle\Entity\Texte_region_forfait $texteRegionForfaitId)
    {
        $this->__load();
        return parent::addTexte_region_forfait($texteRegionForfaitId);
    }

    public function getTexteRegionForfaitId()
    {
        $this->__load();
        return parent::getTexteRegionForfaitId();
    }

    public function addTexte_province_forfait(\MyApp\GlobalBundle\Entity\Texte_province_forfait $texteProvinceForfaitId)
    {
        $this->__load();
        return parent::addTexte_province_forfait($texteProvinceForfaitId);
    }

    public function getTexteProvinceForfaitId()
    {
        $this->__load();
        return parent::getTexteProvinceForfaitId();
    }

    public function setRepertoireFr($repertoireFr)
    {
        $this->__load();
        return parent::setRepertoireFr($repertoireFr);
    }

    public function getRepertoireFr()
    {
        $this->__load();
        return parent::getRepertoireFr();
    }

    public function setRepertoireEn($repertoireEn)
    {
        $this->__load();
        return parent::setRepertoireEn($repertoireEn);
    }

    public function getRepertoireEn()
    {
        $this->__load();
        return parent::getRepertoireEn();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'hebergement_forfait', 'attrait_id', 'forfait_id', 'nom_fr', 'repertoire_fr', 'repertoire_en', 'nom_en', 'meta_titre_fr', 'meta_titre_en', 'page_metakeyword_fr', 'page_metakeyword_en', 'page_metadescription_fr', 'page_metadescription_en', 'texte_fr', 'texte_en', 'default_forfait', 'image', 'image_doctrine', 'texte_region_forfait_id', 'texte_province_forfait_id', 'qcs_forfaits_id', 'qcs_saison_id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}