<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityVillesProxy extends \MyApp\GlobalBundle\Entity\Villes implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNomFr($nomFr)
    {
        $this->__load();
        return parent::setNomFr($nomFr);
    }

    public function getNomFr()
    {
        $this->__load();
        return parent::getNomFr();
    }

    public function setNomEn($nomEn)
    {
        $this->__load();
        return parent::setNomEn($nomEn);
    }

    public function getNomEn()
    {
        $this->__load();
        return parent::getNomEn();
    }

    public function setTexteFr($texteFr)
    {
        $this->__load();
        return parent::setTexteFr($texteFr);
    }

    public function getTexteFr()
    {
        $this->__load();
        return parent::getTexteFr();
    }

    public function setTexteEn($texteEn)
    {
        $this->__load();
        return parent::setTexteEn($texteEn);
    }

    public function getTexteEn()
    {
        $this->__load();
        return parent::getTexteEn();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setPageMetakeywordFr($pageMetakeywordFr)
    {
        $this->__load();
        return parent::setPageMetakeywordFr($pageMetakeywordFr);
    }

    public function getPageMetakeywordFr()
    {
        $this->__load();
        return parent::getPageMetakeywordFr();
    }

    public function setPageMetakeywordEn($pageMetakeywordEn)
    {
        $this->__load();
        return parent::setPageMetakeywordEn($pageMetakeywordEn);
    }

    public function getPageMetakeywordEn()
    {
        $this->__load();
        return parent::getPageMetakeywordEn();
    }

    public function setPageMetadescriptionFr($pageMetadescriptionFr)
    {
        $this->__load();
        return parent::setPageMetadescriptionFr($pageMetadescriptionFr);
    }

    public function getPageMetadescriptionFr()
    {
        $this->__load();
        return parent::getPageMetadescriptionFr();
    }

    public function setPageMetadescriptionEn($pageMetadescriptionEn)
    {
        $this->__load();
        return parent::setPageMetadescriptionEn($pageMetadescriptionEn);
    }

    public function getPageMetadescriptionEn()
    {
        $this->__load();
        return parent::getPageMetadescriptionEn();
    }

    public function setTexteAccueilFr($texteAccueilFr)
    {
        $this->__load();
        return parent::setTexteAccueilFr($texteAccueilFr);
    }

    public function getTexteAccueilFr()
    {
        $this->__load();
        return parent::getTexteAccueilFr();
    }

    public function setTexteAccueilEn($texteAccueilEn)
    {
        $this->__load();
        return parent::setTexteAccueilEn($texteAccueilEn);
    }

    public function getTexteAccueilEn()
    {
        $this->__load();
        return parent::getTexteAccueilEn();
    }

    public function setDefaultHebergement($defaultHebergement)
    {
        $this->__load();
        return parent::setDefaultHebergement($defaultHebergement);
    }

    public function getDefaultHebergement()
    {
        $this->__load();
        return parent::getDefaultHebergement();
    }

    public function setDefaultAttrait($defaultAttrait)
    {
        $this->__load();
        return parent::setDefaultAttrait($defaultAttrait);
    }

    public function getDefaultAttrait()
    {
        $this->__load();
        return parent::getDefaultAttrait();
    }

    public function setReservitId($reservitId)
    {
        $this->__load();
        return parent::setReservitId($reservitId);
    }

    public function getReservitId()
    {
        $this->__load();
        return parent::getReservitId();
    }

    public function setAffiche($affiche)
    {
        $this->__load();
        return parent::setAffiche($affiche);
    }

    public function getAffiche()
    {
        $this->__load();
        return parent::getAffiche();
    }

    public function setCodeMeteoMedia($codeMeteoMedia)
    {
        $this->__load();
        return parent::setCodeMeteoMedia($codeMeteoMedia);
    }

    public function getCodeMeteoMedia()
    {
        $this->__load();
        return parent::getCodeMeteoMedia();
    }

    public function setZoneId(\MyApp\GlobalBundle\Entity\Zones $zoneId)
    {
        $this->__load();
        return parent::setZoneId($zoneId);
    }

    public function getZoneId()
    {
        $this->__load();
        return parent::getZoneId();
    }

    public function setRegionId(\MyApp\GlobalBundle\Entity\Regions $regionId)
    {
        $this->__load();
        return parent::setRegionId($regionId);
    }

    public function getRegionId()
    {
        $this->__load();
        return parent::getRegionId();
    }

    public function addHebergements(\MyApp\GlobalBundle\Entity\Hebergements $hebergementId)
    {
        $this->__load();
        return parent::addHebergements($hebergementId);
    }

    public function getHebergementId()
    {
        $this->__load();
        return parent::getHebergementId();
    }

    public function addAttraits(\MyApp\GlobalBundle\Entity\Attraits $attraitId)
    {
        $this->__load();
        return parent::addAttraits($attraitId);
    }

    public function getAttraitId()
    {
        $this->__load();
        return parent::getAttraitId();
    }

    public function addUtilisateur(\MyApp\GlobalBundle\Entity\Utilisateur $utilisateur)
    {
        $this->__load();
        return parent::addUtilisateur($utilisateur);
    }

    public function getUtilisateur()
    {
        $this->__load();
        return parent::getUtilisateur();
    }

    public function addVideos(\MyApp\GlobalBundle\Entity\Videos $video)
    {
        $this->__load();
        return parent::addVideos($video);
    }

    public function getVideo()
    {
        $this->__load();
        return parent::getVideo();
    }

    public function setPageTitreFr($pageTitreFr)
    {
        $this->__load();
        return parent::setPageTitreFr($pageTitreFr);
    }

    public function getPageTitreFr()
    {
        $this->__load();
        return parent::getPageTitreFr();
    }

    public function setPageTitreEn($pageTitreEn)
    {
        $this->__load();
        return parent::setPageTitreEn($pageTitreEn);
    }

    public function getPageTitreEn()
    {
        $this->__load();
        return parent::getPageTitreEn();
    }

    public function setRepertoireFr($repertoireFr)
    {
        $this->__load();
        return parent::setRepertoireFr($repertoireFr);
    }

    public function getRepertoireFr()
    {
        $this->__load();
        return parent::getRepertoireFr();
    }

    public function setRepertoireEn($repertoireEn)
    {
        $this->__load();
        return parent::setRepertoireEn($repertoireEn);
    }

    public function getRepertoireEn()
    {
        $this->__load();
        return parent::getRepertoireEn();
    }

    public function setNomReservit($nomReservit)
    {
        $this->__load();
        return parent::setNomReservit($nomReservit);
    }

    public function getNomReservit()
    {
        $this->__load();
        return parent::getNomReservit();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'zone_id', 'region_id', 'nom_fr', 'nom_en', 'repertoire_fr', 'repertoire_en', 'page_titre_fr', 'page_titre_en', 'texte_fr', 'texte_en', 'latitude', 'longitude', 'page_metakeyword_fr', 'page_metakeyword_en', 'page_metadescription_fr', 'page_metadescription_en', 'nom_reservit', 'texte_accueil_fr', 'texte_accueil_en', 'default_hebergement', 'default_attrait', 'reservit_id', 'affiche', 'hebergement_id', 'attrait_id', 'utilisateur', 'video', 'code_meteo_media');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}