<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityZonesProxy extends \MyApp\GlobalBundle\Entity\Zones implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getFullPicturePath()
    {
        $this->__load();
        return parent::getFullPicturePath();
    }

    public function uploadPicture()
    {
        $this->__load();
        return parent::uploadPicture();
    }

    public function movePicture()
    {
        $this->__load();
        return parent::movePicture();
    }

    public function removePicture()
    {
        $this->__load();
        return parent::removePicture();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNomFr($nomFr)
    {
        $this->__load();
        return parent::setNomFr($nomFr);
    }

    public function getNomFr()
    {
        $this->__load();
        return parent::getNomFr();
    }

    public function setNomEn($nomEn)
    {
        $this->__load();
        return parent::setNomEn($nomEn);
    }

    public function getNomEn()
    {
        $this->__load();
        return parent::getNomEn();
    }

    public function setRepertoireFr($repertoireFr)
    {
        $this->__load();
        return parent::setRepertoireFr($repertoireFr);
    }

    public function getRepertoireFr()
    {
        $this->__load();
        return parent::getRepertoireFr();
    }

    public function setRepertoireEn($repertoireEn)
    {
        $this->__load();
        return parent::setRepertoireEn($repertoireEn);
    }

    public function getRepertoireEn()
    {
        $this->__load();
        return parent::getRepertoireEn();
    }

    public function setTitreFr($titreFr)
    {
        $this->__load();
        return parent::setTitreFr($titreFr);
    }

    public function getTitreFr()
    {
        $this->__load();
        return parent::getTitreFr();
    }

    public function setTitreEn($titreEn)
    {
        $this->__load();
        return parent::setTitreEn($titreEn);
    }

    public function getTitreEn()
    {
        $this->__load();
        return parent::getTitreEn();
    }

    public function setTexteFr($texteFr)
    {
        $this->__load();
        return parent::setTexteFr($texteFr);
    }

    public function getTexteFr()
    {
        $this->__load();
        return parent::getTexteFr();
    }

    public function setTexteEn($texteEn)
    {
        $this->__load();
        return parent::setTexteEn($texteEn);
    }

    public function getTexteEn()
    {
        $this->__load();
        return parent::getTexteEn();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setImageHautFr($imageHautFr)
    {
        $this->__load();
        return parent::setImageHautFr($imageHautFr);
    }

    public function getImageHautFr()
    {
        $this->__load();
        return parent::getImageHautFr();
    }

    public function setImageHautEn($imageHautEn)
    {
        $this->__load();
        return parent::setImageHautEn($imageHautEn);
    }

    public function getImageHautEn()
    {
        $this->__load();
        return parent::getImageHautEn();
    }

    public function setImageGauche($imageGauche)
    {
        $this->__load();
        return parent::setImageGauche($imageGauche);
    }

    public function getImageGauche()
    {
        $this->__load();
        return parent::getImageGauche();
    }

    public function setImageCentre($imageCentre)
    {
        $this->__load();
        return parent::setImageCentre($imageCentre);
    }

    public function getImageCentre()
    {
        $this->__load();
        return parent::getImageCentre();
    }

    public function setPageTitreFr($pageTitreFr)
    {
        $this->__load();
        return parent::setPageTitreFr($pageTitreFr);
    }

    public function getPageTitreFr()
    {
        $this->__load();
        return parent::getPageTitreFr();
    }

    public function setPageTitreEn($pageTitreEn)
    {
        $this->__load();
        return parent::setPageTitreEn($pageTitreEn);
    }

    public function getPageTitreEn()
    {
        $this->__load();
        return parent::getPageTitreEn();
    }

    public function setPageMetakeywordFr($pageMetakeywordFr)
    {
        $this->__load();
        return parent::setPageMetakeywordFr($pageMetakeywordFr);
    }

    public function getPageMetakeywordFr()
    {
        $this->__load();
        return parent::getPageMetakeywordFr();
    }

    public function setPageMetakeywordEn($pageMetakeywordEn)
    {
        $this->__load();
        return parent::setPageMetakeywordEn($pageMetakeywordEn);
    }

    public function getPageMetakeywordEn()
    {
        $this->__load();
        return parent::getPageMetakeywordEn();
    }

    public function setPageMetadescriptionFr($pageMetadescriptionFr)
    {
        $this->__load();
        return parent::setPageMetadescriptionFr($pageMetadescriptionFr);
    }

    public function getPageMetadescriptionFr()
    {
        $this->__load();
        return parent::getPageMetadescriptionFr();
    }

    public function setPageMetadescriptionEn($pageMetadescriptionEn)
    {
        $this->__load();
        return parent::setPageMetadescriptionEn($pageMetadescriptionEn);
    }

    public function getPageMetadescriptionEn()
    {
        $this->__load();
        return parent::getPageMetadescriptionEn();
    }

    public function setRegionId(\MyApp\GlobalBundle\Entity\Regions $regionId)
    {
        $this->__load();
        return parent::setRegionId($regionId);
    }

    public function getRegionId()
    {
        $this->__load();
        return parent::getRegionId();
    }

    public function addVilles(\MyApp\GlobalBundle\Entity\Villes $villeId)
    {
        $this->__load();
        return parent::addVilles($villeId);
    }

    public function getVilleId()
    {
        $this->__load();
        return parent::getVilleId();
    }

    public function addAttraits(\MyApp\GlobalBundle\Entity\Attraits $attraitId)
    {
        $this->__load();
        return parent::addAttraits($attraitId);
    }

    public function getAttraitId()
    {
        $this->__load();
        return parent::getAttraitId();
    }

    public function addHebergements(\MyApp\GlobalBundle\Entity\Hebergements $hebergementId)
    {
        $this->__load();
        return parent::addHebergements($hebergementId);
    }

    public function getHebergementId()
    {
        $this->__load();
        return parent::getHebergementId();
    }

    public function setTexteResumeFr($texteResumeFr)
    {
        $this->__load();
        return parent::setTexteResumeFr($texteResumeFr);
    }

    public function getTexteResumeFr()
    {
        $this->__load();
        return parent::getTexteResumeFr();
    }

    public function setTexteResumeEn($texteResumeEn)
    {
        $this->__load();
        return parent::setTexteResumeEn($texteResumeEn);
    }

    public function getTexteResumeEn()
    {
        $this->__load();
        return parent::getTexteResumeEn();
    }

    public function setImageSuggestion($imageSuggestion)
    {
        $this->__load();
        return parent::setImageSuggestion($imageSuggestion);
    }

    public function getImageSuggestion()
    {
        $this->__load();
        return parent::getImageSuggestion();
    }

    public function setImageSuggestionDoctrine($imageSuggestionDoctrine)
    {
        $this->__load();
        return parent::setImageSuggestionDoctrine($imageSuggestionDoctrine);
    }

    public function getImageSuggestionDoctrine()
    {
        $this->__load();
        return parent::getImageSuggestionDoctrine();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'region_id', 'nom_fr', 'nom_en', 'titre_fr', 'titre_en', 'texte_fr', 'texte_en', 'latitude', 'longitude', 'image_haut_fr', 'image_haut_en', 'image_gauche', 'image_centre', 'image_suggestion', 'image_suggestion_doctrine', 'page_metakeyword_fr', 'page_metakeyword_en', 'page_metadescription_fr', 'page_metadescription_en', 'texte_resume_fr', 'texte_resume_en', 'repertoire_fr', 'repertoire_en', 'ville_id', 'attrait_id', 'hebergement_id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}