<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityDescription_frProxy extends \MyApp\GlobalBundle\Entity\Description_fr implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setTexteGeneraleChambreFr($texteGeneraleChambreFr)
    {
        $this->__load();
        return parent::setTexteGeneraleChambreFr($texteGeneraleChambreFr);
    }

    public function getTexteGeneraleChambreFr()
    {
        $this->__load();
        return parent::getTexteGeneraleChambreFr();
    }

    public function setTexteDirectionRoutierePersoFr($texteDirectionRoutierePersoFr)
    {
        $this->__load();
        return parent::setTexteDirectionRoutierePersoFr($texteDirectionRoutierePersoFr);
    }

    public function getTexteDirectionRoutierePersoFr()
    {
        $this->__load();
        return parent::getTexteDirectionRoutierePersoFr();
    }

    public function addHebergements(\MyApp\GlobalBundle\Entity\Hebergements $hebergementDescriptionFr)
    {
        $this->__load();
        return parent::addHebergements($hebergementDescriptionFr);
    }

    public function getHebergementDescriptionFr()
    {
        $this->__load();
        return parent::getHebergementDescriptionFr();
    }

    public function setDescriptionPromotionFr($descriptionPromotionFr)
    {
        $this->__load();
        return parent::setDescriptionPromotionFr($descriptionPromotionFr);
    }

    public function getDescriptionPromotionFr()
    {
        $this->__load();
        return parent::getDescriptionPromotionFr();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'texte_generale_chambre_fr', 'texte_direction_routiere_perso_fr', 'description_promotion_fr', 'hebergement_description_fr');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}