<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityPolitique_enProxy extends \MyApp\GlobalBundle\Entity\Politique_en implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setPolitiqueGeneraleEn($politiqueGeneraleEn)
    {
        $this->__load();
        return parent::setPolitiqueGeneraleEn($politiqueGeneraleEn);
    }

    public function getPolitiqueGeneraleEn()
    {
        $this->__load();
        return parent::getPolitiqueGeneraleEn();
    }

    public function setPolitiqueAnimauxEn($politiqueAnimauxEn)
    {
        $this->__load();
        return parent::setPolitiqueAnimauxEn($politiqueAnimauxEn);
    }

    public function getPolitiqueAnimauxEn()
    {
        $this->__load();
        return parent::getPolitiqueAnimauxEn();
    }

    public function setPolitiqueAnnulationEn($politiqueAnnulationEn)
    {
        $this->__load();
        return parent::setPolitiqueAnnulationEn($politiqueAnnulationEn);
    }

    public function getPolitiqueAnnulationEn()
    {
        $this->__load();
        return parent::getPolitiqueAnnulationEn();
    }

    public function setPolitiqueTarifEn($politiqueTarifEn)
    {
        $this->__load();
        return parent::setPolitiqueTarifEn($politiqueTarifEn);
    }

    public function getPolitiqueTarifEn()
    {
        $this->__load();
        return parent::getPolitiqueTarifEn();
    }

    public function setPolitiqueAnnulationForfaitEn($politiqueAnnulationForfaitEn)
    {
        $this->__load();
        return parent::setPolitiqueAnnulationForfaitEn($politiqueAnnulationForfaitEn);
    }

    public function getPolitiqueAnnulationForfaitEn()
    {
        $this->__load();
        return parent::getPolitiqueAnnulationForfaitEn();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'politique_generale_en', 'politique_annulation_forfait_en', 'politique_animaux_en', 'politique_annulation_en', 'politique_tarif_en');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}