<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityDescription_enProxy extends \MyApp\GlobalBundle\Entity\Description_en implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setTexteGeneraleChambreEn($texteGeneraleChambreEn)
    {
        $this->__load();
        return parent::setTexteGeneraleChambreEn($texteGeneraleChambreEn);
    }

    public function getTexteGeneraleChambreEn()
    {
        $this->__load();
        return parent::getTexteGeneraleChambreEn();
    }

    public function setTexteDirectionRoutierePersoEn($texteDirectionRoutierePersoEn)
    {
        $this->__load();
        return parent::setTexteDirectionRoutierePersoEn($texteDirectionRoutierePersoEn);
    }

    public function getTexteDirectionRoutierePersoEn()
    {
        $this->__load();
        return parent::getTexteDirectionRoutierePersoEn();
    }

    public function addHebergements(\MyApp\GlobalBundle\Entity\Hebergements $hebergementDescriptionEn)
    {
        $this->__load();
        return parent::addHebergements($hebergementDescriptionEn);
    }

    public function getHebergementDescriptionEn()
    {
        $this->__load();
        return parent::getHebergementDescriptionEn();
    }

    public function setDescriptionPromotionEn($descriptionPromotionEn)
    {
        $this->__load();
        return parent::setDescriptionPromotionEn($descriptionPromotionEn);
    }

    public function getDescriptionPromotionEn()
    {
        $this->__load();
        return parent::getDescriptionPromotionEn();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'texte_generale_chambre_en', 'texte_direction_routiere_perso_en', 'description_promotion_en', 'hebergement_description_en');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}