<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyAppGlobalBundleEntityPolitique_frProxy extends \MyApp\GlobalBundle\Entity\Politique_fr implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setPolitiqueGeneraleFr($politiqueGeneraleFr)
    {
        $this->__load();
        return parent::setPolitiqueGeneraleFr($politiqueGeneraleFr);
    }

    public function getPolitiqueGeneraleFr()
    {
        $this->__load();
        return parent::getPolitiqueGeneraleFr();
    }

    public function setPolitiqueAnimauxFr($politiqueAnimauxFr)
    {
        $this->__load();
        return parent::setPolitiqueAnimauxFr($politiqueAnimauxFr);
    }

    public function getPolitiqueAnimauxFr()
    {
        $this->__load();
        return parent::getPolitiqueAnimauxFr();
    }

    public function setPolitiqueAnnulationFr($politiqueAnnulationFr)
    {
        $this->__load();
        return parent::setPolitiqueAnnulationFr($politiqueAnnulationFr);
    }

    public function getPolitiqueAnnulationFr()
    {
        $this->__load();
        return parent::getPolitiqueAnnulationFr();
    }

    public function setPolitiqueTarifFr($politiqueTarifFr)
    {
        $this->__load();
        return parent::setPolitiqueTarifFr($politiqueTarifFr);
    }

    public function getPolitiqueTarifFr()
    {
        $this->__load();
        return parent::getPolitiqueTarifFr();
    }

    public function setPolitiqueAnnulationForfaitFr($politiqueAnnulationForfaitFr)
    {
        $this->__load();
        return parent::setPolitiqueAnnulationForfaitFr($politiqueAnnulationForfaitFr);
    }

    public function getPolitiqueAnnulationForfaitFr()
    {
        $this->__load();
        return parent::getPolitiqueAnnulationForfaitFr();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'politique_generale_fr', 'politique_annulation_forfait_fr', 'politique_animaux_fr', 'politique_annulation_fr', 'politique_tarif_fr');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}